name: ESLint Check

on:
  push:
    branches:
      - "**"

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
